# https://mise.jdx.dev/configuration.html
[tools]
node = "23.7.0"
"npm:pnpm" = "10.2.0"

[hooks]
postinstall = [
  "mise run install-deps",
  "mise generate git-pre-commit --write --task=pre-commit"
]

[tasks.pre-commit]
description = 'Runs pre-commit tasks'
depends = ['format', 'lint']

[tasks.install-deps]
description = 'Installs dependencies'
run = 'pnpm install'
sources = ['package.json', 'pnpm-lock.yaml', 'mise.toml']
outputs = ['node_modules/.pnpm/lock.yaml']

[tasks.build]
description = 'Builds the project'
run = 'pnpm exec tsc -p tsconfig.build.json'

[tasks.watch]
description = 'Watches the project for changes'
run = 'pnpm exec tsc -p tsconfig.build.json --watch'

[tasks.test-watch]
alias = 'test'
description = 'Runs tests in watch mode'
run = 'pnpm exec vitest'

[tasks.test-run]
description = 'Runs tests'
run = 'pnpm exec vitest run'

[tasks.format]
description = 'Formats the project'
run = "pnpm exec biome format --write"

[tasks.lint]
description = 'Lints the project'
run = "pnpm exec biome lint"

[tasks.lint-fix]
description = 'Lints the project and fixes issues'
run = "pnpm exec biome lint --fix"

[settings]
experimental = true