edition = "2024"
max_width = 100
use_small_heuristics = "Max"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# インポート管理
reorder_imports = true
reorder_modules = true
group_imports = "StdExternalCrate"
imports_layout = "Vertical"

# コード品質向上
remove_nested_parens = true
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true

# 一貫性保証
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false

# 関数とマクロ
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# コメントとドキュメント
normalize_comments = true
normalize_doc_attributes = true
